chore(deps): update metabase/metabase docker tag to v0.53.1 (#113)
* chore(deps): update metabase/metabase docker tag to v0.53.1

* fix: startup and metaspace size

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Om Mishra <32200996+mishraomp@users.noreply.github.com>

diff --git a/charts/nr-metabase/templates/metabase/configmap.yaml b/charts/nr-metabase/templates/metabase/configmap.yaml
--- a/charts/nr-metabase/templates/metabase/configmap.yaml
+++ b/charts/nr-metabase/templates/metabase/configmap.yaml
@@ -54,9 +54,9 @@ data:
             read -ra strarr <<<"${DB_HOST_PORT}"
             DB_HOST="${strarr[0]}"
             DB_PORT="${strarr[1]}"
-            openssl s_client -connect "${DB_HOST}:${DB_PORT}" -showcerts </dev/null 2>/dev/null | openssl x509 -outform pem >"$cert_folder/${DB_HOST}.pem" 2>/dev/null || exit 1
-            openssl x509 -outform der -in "$cert_folder/${DB_HOST}.pem" -out "$cert_folder/${DB_HOST}.der" 2>/dev/null || exit 1
-            keytool -import -alias "orakey-${DB_HOST}-1" -keystore "${JAVA_HOME}"/lib/security/cacerts -storepass changeit -file "$cert_folder/${DB_HOST}.der" -noprompt >/dev/null 2>&1 || exit 1
+            openssl s_client -connect "${DB_HOST}:${DB_PORT}" -showcerts </dev/null 2>/dev/null | openssl x509 -outform pem >"$cert_folder/${DB_HOST}.pem" 2>/dev/null || echo "failed connecting to $DB_HOST"
+            openssl x509 -outform der -in "$cert_folder/${DB_HOST}.pem" -out "$cert_folder/${DB_HOST}.der" 2>/dev/null || echo "failed in creating pem file for $DB_HOST"
+            keytool -import -alias "orakey-${DB_HOST}-1" -keystore "${JAVA_HOME}"/lib/security/cacerts -storepass changeit -file "$cert_folder/${DB_HOST}.der" -noprompt >/dev/null 2>&1 || echo "failed in import cert for $DB_HOST"
         done
 
         echo -e "\033[1;33m=====================================\033[0m"
@@ -70,7 +70,7 @@ data:
 
 
         if [ -f /config/log4j2.xml ]; then
-            java -server -Duser.name=metabase -Xms${MIN_HEAP} -Xmx${MAX_HEAP} -XX:TieredStopAtLevel=4 -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=200m -XX:+ExitOnOutOfMemoryError -Dlog4j.configurationFile=file:/config/log4j2.xml -jar metabase.jar
+            java -server -Duser.name=metabase -Xms${MIN_HEAP} -Xmx${MAX_HEAP} -XX:TieredStopAtLevel=4 -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=400m -XX:+ExitOnOutOfMemoryError -Dlog4j.configurationFile=file:/config/log4j2.xml -jar metabase.jar
         else
-            java -server -Duser.name=metabase -Xms${MIN_HEAP} -Xmx${MAX_HEAP} -XX:TieredStopAtLevel=4 -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=200m -XX:+ExitOnOutOfMemoryError -jar metabase.jar
+            java -server -Duser.name=metabase -Xms${MIN_HEAP} -Xmx${MAX_HEAP} -XX:TieredStopAtLevel=4 -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=400m -XX:+ExitOnOutOfMemoryError -jar metabase.jar
         fi
